language: python
python:
  - "3.6" # current default Python on Travis CI

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover -v

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - git config --local user.name "Gabriel Barker"
  - git config --local user.email "$GITHUB_EMAIL"
  - name=$(bin/qual-id.sh -p bird-instrument)
  - tag="${name%\"}"
  - tag="${tag#\"}"
  - git tag $tag
  - mkdir $tag
  - cp bin/qual-id.sh $tag/
  - cp README.md LICENSE $tag/
  - tar czvf $tag.tar.gz $tag

deploy:
  provider: releases
  api_key:
    secure: FNNd4lrwKk6Qnv0fJMmtDJjOKI++oaMfqCOByj2G10GOOxjPngm/+WWkhRaUl6lXTuRKLC7L7zmNcPoOqdB6cwZZjEGADUuOQuzF8VUlMX9VDERVFoMNldGKH1dXUK8+0so/siZwZcPRvJqb4KSlQ9rCcu5VR7fV+A/lZpM30cgbnM1wP8vypl+8HNS+hqgutlNtalgNFpHoTV62IdVovv0KUw3iPmA1na/xBk8/tixA8T3Kps35gsNS1uc8bz3yoXzkr/84Qg2RM37soEDbxT/kCp2/v5B0Ake/LfN8KSSPcWoJt01mEazSDRBJs8eMjaBbtgE1ExFLBD3pD9b3WX6JgEwpiLJpHuAPZz/wFGqCDoLxb8ZkbQ/Qt1pkCzGizlX2tpi8auAM3Ur+ZMWg0aZtJ7ZsXyDHj95eSe0wdQD1PyjIuoy3qqaxqUlf0L897IYfiHShPIjTM08My3hDcbixnJz77Yg7nZnuVY/DvsCmoH+sHxUSH9SWE4cuexGqIjiVIpDs6O/ch1xou5VjW2nLmDOc7Q3W+hab9yD57WzJCNbykSyju/qQATAtMO61bB3SfewHl5x3J7vTnAkC9hmeh4RyPp7cc4VVuy0zKXjIsx7VBm9Fj0R3W+YnSfZcmfwTW5WzLjqA+WVNYCTBgRhbNf0P7y9PNhNQSFIpU/M=
  file: $tag.tar.gz
  on:
    repo: gabrielbarker/qual-id
    branch: main
  skip_cleanup: true
