language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - coverage run -m unittest discover -v
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - git config --local user.name "Gabriel Barker"
  - git config --local user.email "$GITHUB_EMAIL"
  - name=$(bin/qual-id -p bird-instrument)
  - tag="${name%\"}"
  - tag="${tag#\"}"
  - git tag $tag
  - mkdir $tag
  - cp -R qual_id/ $tag/qual_id/
  - cp cli.py $tag/
  - mv $tag/cli.py $tag/qual-id
  - cp README.md LICENSE $tag/
  - tar czvf $tag.tar.gz $tag
deploy:
  provider: releases
  api_key:
    secure: I6l2K5XOnkUwPr4Bgf7etsKXd3tHpNg+apvXvPgQOCkK6q2KWHmBacbzXZaqZApT+HOweatU4XWi5Zg9b+SywksTCbTOcWHv980hp4+JPMBdpypc088iLzsyLhJGnf76nUJzRGMOYiGXksstajzyh/7DfSMa/vthUMGe1MKKkPOz4rcIhvz6Av6IlQndOYkYWHX77j+6xrnjAGNoM267YJkRLSFf1CqqoBCMuhzakg0jQPAlLzqRBp0A6GuT/dkarmU1FxO7l1Nm1mJx6BmDTdEF9HPOW53Jjp9K75GBpVuentXvXVK+5+32JxSxHRxb4y+JzDxen48TznbjcN9SXhYyKr/l/kjOAbTV9AGBrUN1XHPVOhJr6Nf+o4By485ZxpLkI3G5bM71PrYDlGWBtDa+EB6YM7nKlwxFqD7jcjhWV/fjxGUpG21fWfopl4AQEgsU0YC12mqb2N0WEmPbSD4Eku3LK9OkH751rDwNH0OS6mnYzLn2MaddnpcL3fNly2NoX/VsjQcsFHwfIaRuvDiCUAlQi42UBsQi6gXSsB8nTAiRf/NvRNeH0c03TT1Cas0Ci68RsBOr9dLSlM3EUD+UcjYMI/sreBkxjFN4wAlnSEndWiAskQRYlJ84rYsnupCF0XyX3voohhBedw8tnxbBaaE0kfN+l/hmaCKqbc8=
  file: $tag.tar.gz
  on:
    repo: gabrielbarker/qual-id
    branch: main
  skip_cleanup: "true"
